language: node_js
cache:
  yarn: true
node_js:
- '8.4'

jobs:
  include:
    - stage: Tests
      node_js: node
      script: 
        - jest src --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - npm run e2e
        